name: Java CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile with Maven
      run: mvn compile
    - name: Code Review with Maven
      run: mvn pmd:pmd
    - name: Testing with Maven
      run: mvn test  
    - name: CoverageChecks with Maven
      run: mvn cobertura:cobertura -Dcobertura.report.format=xml
    #- name: Sonar Verify
     # run: mvn verify sonar:sonar  
    - name: Build with Maven
      run: mvn package
  
  #deploy:
  #  runs-on: ubuntu-latest
   # name: Docker push
   # needs: [build]
   # steps:
  #  - uses: actions/checkout@v1
    - name: Copy war file
      run: cp /home/runner/work/DevOps-Demo/DevOps-Demo/target/addressbook.war .
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vishwasnm2/devopsdemo:0.1
    - name: Docker credentials
      run: docker login --username vishwasnm2 --password ${{secrets.DOCKERHUB_AUTH}} 
    - name: Pushing the image on DockerHub
      run: docker push vishwasnm2/devopsdemo:0.1
        
  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHE_AUTH }}
  aritifacts:             
    name: Publish Maven Artifacts
    runs-on: ubuntu-latest
    needs: [build, sonar]
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish artifact on GitHub Packages
        run: mvn deploy
        env:
         GITHUB_TOKEN: ${{secrets.GHE_AUTH}}  #npm_token
